### ISSUE TITLE
Error in Safari iOS 10

### ISSUE THREAD

**Issue by mahaveer0496** [gnir-work/react-window-dynamic-list#21]
This package doesn't work in Safari on iOS 10. 

Steps to reproduce - 
* Go to https://gnir-work.github.io/react-window-dynamic-list/ 

Error -
![image](https://user-images.githubusercontent.com/23198481/86279661-03e76000-bbf8-11ea-8243-2a6643d14322.png)

This is not specific to browser stack, ive tested on actual devices as well.

**Comment by gnir-work** [comment]
Hey, sorry for the late reply.
Currently I am not going to support IOS :(
You are more than welcomed to open a PR that fixes this issue, until then I am closing this thread.
