### ISSUE TITLE
Property ref is missing on DynamicListProps

### ISSUE THREAD

**Issue by dkluhzeb** [gnir-work/react-window-dynamic-list#23]
I've tried to access the list via an ref, but my typscript transpiler is crying.

![Screenshot_20201013_122828](https://user-images.githubusercontent.com/7802258/95849895-47517e80-0d50-11eb-8484-c5f6647de4f0.png)

Technically the forwarded ref works, but i have to ignore typing here:
![Screenshot_20201013_123003](https://user-images.githubusercontent.com/7802258/95849972-64864d00-0d50-11eb-8010-05f3bcd52db4.png)

I really like your Project, thanks for sharing this!

**Comment by gnir-work** [comment]
Thanks for the feedback 😊
I will take a look into the typing and update accordingly

**Comment by gnir-work** [comment]
Fixed in latest version :)
You can update via `npm i react-window-dynamic-list@2.4.0` in order to recieve the changes.
I am closing the issue for now, in case something else pops up you are more than welcomed to reopen it.
