### ISSUE TITLE
Changes to the lists scrollbar?

### ISSUE THREAD

**Issue by burtonator** [gnir-work/react-window-dynamic-list#7]
What do you mean by this note:

> Changes to the list's scrollbar, especially the width, should effect all of the scrollbars in the application. Since we pre render the items in order to measure them the size of the scrollbar is important in the pre rendered item as well.

Do you mean the CSS for the actually physical scrollbar that you drag in the UI ?  

I imagine this won't impact many people as most people don't change this

**Comment by gnir-work** [comment]
Thats what I meant.
I know that it won't impact many people, however I think it should still be
written somewhere :)

**Comment by gnir-work** [comment]
I am closing this thread, feel free to open it again if you have any more questions.
