### ISSUE TITLE
Typescript types...

### ISSUE THREAD

**Issue by burtonator** [gnir-work/react-window-dynamic-list#8]
We need typescript types.  I can submit a .ts file if you guys want. Going to test this in my app as I need it in two major places.

**Comment by gnir-work** [comment]
I am not sure how adding typescript will affect the build process.
I will probably have time to check this out in the weekend 😊

**Comment by JbPons** [comment]
Hi,

Any news here ? I work on a project use React typescript, and I really want to use this library. I can help on Typescript type if you need it.

**Comment by gnir-work** [comment]
Ill probably get to it in the next few days :)

**Comment by amocarski** [comment]
@gnir-work any updates?

**Comment by gnir-work** [comment]
First of all I am sorry for the delayed response guys, the past month was really intense for me...
Luckily I had some time today so I added support for typescript 🥳.

Please run `npm i react-window-dynamic-list@latest`, the support is from version `2.3.5` and above.

In case any of you come across any bugs or wrong types please let me now, 
in the mean time I am closing the issue.
Cheers 🐻
